I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 158, in script
    hide bg with fadeout
  File "game/script.rpy", line 158, in <module>
    hide bg with fadeout
NameError: name 'fadeout' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 158, in script
    hide bg with fadeout
  File "C:\Users\alext\OneDrive - Universidade de Lisboa\Documentos\Programas\renpy-8.0.0-sdk\renpy\ast.py", line 1634, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Users\alext\OneDrive - Universidade de Lisboa\Documentos\Programas\renpy-8.0.0-sdk\renpy\python.py", line 1080, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\alext\OneDrive - Universidade de Lisboa\Documentos\Programas\renpy-8.0.0-sdk\renpy\python.py", line 1073, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 158, in <module>
    hide bg with fadeout
NameError: name 'fadeout' is not defined

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.0.22062402
Cozy Autumn Game Jam 
Fri Sep 23 00:29:08 2022
